---
- name: update server
  apt: upgrade=dist

- name: install dependencies
  apt: name={{ item }} state=present update_cache=yes
    with_items:
        - build-essential
        - libevent-dev
        - libssl-dev
        - liblzma-dev
        - python-dev
        - python-pip
        - swig
